---

dist: focal

services:
  - docker

stages:
  - Static test
  - Build test

jobs:
  include:
    - stage: Static test-1-amd64
      env:
        - Test: hadolint
      language: minimal
      script:
        - docker run --rm -i -v $PWD/.hadolint.yml:/.hadolint.yml hadolint/hadolint < Dockerfile

    - stage: Static test-2-amd64
      env:
        - Test: dockerfile_lint
      language: node_js
      node_js:
        - "12"
      script:
        - npx --cache .npx dockerfile_lint
      cache:
        directories:
          - .npx

    - stage: Build test-amd64
      arch: amd64
      language: minimal
      before_script:
        - LATEST_AZCOPY="$(curl -sLo- https://api.github.com/repos/Azure/azure-storage-azcopy/releases | jq -r '.[0].tag_name' | sed 's/^v//g')"
        - test -n "$LATEST_AZCOPY"
        - export LATEST_AZCOPY
      script:
        - docker build --build-arg AZCOPY_VERSION="$LATEST_AZCOPY" -t $DOCKER_USERNAME/docker-azcopy:$TRAVIS_COMMIT -t $DOCKER_USERNAME/docker-azcopy:"$LATEST_AZCOPY" .
      after_success:
        - docker run --rm $DOCKER_USERNAME/docker-azcopy:"$LATEST_AZCOPY" azcopy --version

deploy:
  provider: <provider>
  # ⋮
  on:
    tags: true
  script:
       - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
       - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
           docker push $DOCKER_USERNAME/docker-azcopy:$AZCOPY_VERSION-arm64 .
         else
           docker push $DOCKER_USERNAME/docker-azcopy:$AZCOPY_VERSION .
         fi
