---

dist: focal

services:
  - docker

stages:
  - Static test

jobs:
  include:
    - stage: Build test
      language: minimal
      before_script:
        - LATEST_AZCOPY="$(curl -sSLo- https://api.github.com/repos/Azure/azure-storage-azcopy/releases | jq -r '.[0].tag_name' | sed 's/^v//g')"
        - test -n "$LATEST_AZCOPY"
        - export LATEST_AZCOPY
      script:
        - IN="$LATEST_AZVOPY"
        - tag=(`echo $IN | tr '.' ' '`) 
        - tag1 = ${tag[0]}.${tag[1]}
        - tag2 = ${tag[0]}
        - docker build --build-arg AZCOPY_VERSION="$LATEST_AZCOPY" -t docker-azcopy:$tag1 -t docker-azcopy:$tag2 .
