---

dist: focal

services:
  - docker

stages:
  - Build test

jobs:
  include:
    - stage: Build test
      language: minimal
      before_script:
        - LATEST_AZCOPY="$(curl -sLo- https://api.github.com/repos/Azure/azure-storage-azcopy/releases | jq -r '.[0].tag_name' | sed 's/^v//g')"
        - test -n "$LATEST_AZCOPY"
        - export LATEST_AZCOPY
      script:
        - tag1=$(echo "$LATEST_AZCOPY" | tr '.' '\n' | head -1)
        - echo $tag1
        - tag2=$(echo "$LATEST_AZCOPY" | tr '.' '\n' | head -2)
        - echo $tag2
        - cat $tag2 | sed -e 's/\s/./g' > tag3
        - echo $tag3
