---

dist: focal

services:
  - docker

stages:
  - Static test
  - Build test

jobs:
  include:
    - stage: Static test
      env:
        - Test: hadolint
      language: minimal
      script:
        - docker run --rm -i -v $PWD/.hadolint.yml:/.hadolint.yml hadolint/hadolint < Dockerfile

    - stage: Static test
      env:
        - Test: dockerfile_lint
      language: node_js
      node_js:
        - "12"
      script:
        - npx --cache .npx dockerfile_lint
      cache:
        directories:
          - .npx

    - stage: Build test
      language: minimal
      before_script:
        - LATEST_AZCOPY="$(curl -sLo- https://api.github.com/repos/Azure/azure-storage-azcopy/releases | jq -r '.[0].tag_name' | sed 's/^v//g')"
        - test -n "$LATEST_AZCOPY"
        - export LATEST_AZCOPY
      script:
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - docker buildx create --name mybuilder
        - docker buildx use
        - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        - travis_wait 30 docker buildx build --build-arg AZCOPY_VERSION="$LATEST_AZCOPY" -t $DOCKER_USERNAME/docker-azcopy:$LATEST_AZCOPY -t $DOCKER_USERNAME/docker-azcopy:latest --platform linux/amd64,linux/arm64 --push .
        - docker buildx rm mybuilder
