---

dist: focal

services:
  - docker

stages:
  - Build test

jobs:
  include:
    - stage: Build test
      language: minimal
      before_script:
        - LATEST_AZCOPY="$(curl -sLo- https://api.github.com/repos/Azure/azure-storage-azcopy/releases | jq -r '.[0].tag_name' | sed 's/^v//g')"
        - test -n "$LATEST_AZCOPY"
        - export LATEST_AZCOPY
      script: 
        - IN="$LATEST_AZCOPY"
        - arr=(`echo $IN | tr '.' ' '`)
        - echo ${arr[0]}
        - echo ${arr[0]}.${arr[1]}
